PATH := ~/.solc-select/artifacts/:~/.solc-select/artifacts/solc-0.5.12:~/.solc-select/artifacts/solc-0.6.12:~/.solc-select/artifacts/solc-0.8.21:$(PATH)
certora-urn                :; PATH=${PATH} certoraRun certora/LockstakeUrn.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-lssky              :; PATH=${PATH} certoraRun certora/LockstakeSky.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-engine             :; PATH=${PATH} certoraRun certora/LockstakeEngine.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-engine-multicall   :; PATH=${PATH} certoraRun certora/LockstakeEngineMulticall.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-clipper            :; PATH=${PATH} certoraRun certora/LockstakeClipper.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-migrator           :; PATH=${PATH} certoraRun certora/LockstakeMigrator.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
certora-capped-osm         :; PATH=${PATH} certoraRun certora/LockstakeCappedOsmWrapper.conf$(if $(rule), --rule $(rule),)$(if $(results), --wait_for_results all,)
