name: Certora

on: [push, pull_request]

jobs:
  certora:
    name: Certora
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lockstake:
          - urn
          - lsmkr
          - engine
          - engine-multicall
          - clipper

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jre

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install solc-select
        run: pip3 install solc-select

      - name: Solc Select 0.8.21
        run: solc-select install 0.8.21

      - name: Solc Select 0.6.12
        run: solc-select install 0.6.12

      - name: Solc Select 0.5.12
        run: solc-select install 0.5.12

      - name: Install Certora
        run: pip3 install certora-cli-beta

      - name: Verify ${{ matrix.lockstake }}
        run: make certora-${{ matrix.lockstake }} results=1
        env:
          CERTORAKEY: ${{ secrets.CERTORAKEY }}
